### ISSUE TITLE
Caption url and relative source folder path

### ISSUE THREAD

**Issue by drallgood** [MartinThoma/jekyll-caption-tag#6] opened 2014-04-18 12:16 UTC
When using `source: source` instead of `source: /absolute/path/to/source` you get absolute urls as caption urls.

This is especially important when you're building the site on different machines (e.g. multi user setup or when using a build server)

**Comment by MartinThoma** [comment] 2014-04-18 12:20
What do you mean? Do you mean users can / should assign different values for `url`? Do you mean I should change `get_image_path`? In what way should I change it?

Is this probably a duplicate of issue #4?

**Comment by drallgood** [comment] 2014-04-18 12:52
No, this has something to do with the way the online url is generated. So you'd need to change `get_online_url`.

Right now, it takes the absolute path of the newly created thumbnail and "removes" the first n-1 characters. n being the length of the `site.source` variable (from _config.yml).

**Comment by MartinThoma** [comment] 2014-04-18 13:05
I'm sorry, I still don't understand what you mean with

> When using `source: source` instead of `source: /absolute/path/to/source` you get absolute urls as caption urls.

As the change seems to be relatively short, could you please write how exactly you would change `get_online_url`?

**Comment by drallgood** [comment] 2014-04-18 13:14
```
def get_online_url(baseurl, caption_folder, dirname,  new_filename)
        dest = File.join(baseurl, caption_folder, new_filename[dirname.length..-1])
        return dest
end
```

**Comment by drallgood** [comment] 2014-04-18 13:17
It uses the dirname (absolute path to the caption folder) to get the filename of the newly created caption file and then prepends it with the base url and the name of the caption folder.
Result (on my system): `/captions/2G3A8950-22.jpg`

**Comment by MartinThoma** [comment] 2014-04-18 14:07
Ah, I see. I've changed that (see [line 156ff](https://github.com/MartinThoma/jekyll-caption-tag/blob/master/caption_tag.rb#L156)).

**Closed as completed** 2014-04-18 14:07 UTC

**Comment by drallgood** [comment] 2014-04-18 14:17
Awesome. That fixed it :)
